services:
  filedpapers-web:
    image: ghcr.io/svenkubiak/filedpapers/filedpapers:${VERSION}
    container_name: filedpapers-web
    restart: always
    env_file:
      - .env
    environment:
      JAVA_OPTS: >
        -Dapplication.config=/app/config/config.yaml  
        -Xms512m
        -Xmx512m
        -XX:+UseCompactObjectHeaders
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config:/app/config
      - ./logs:/logs
    depends_on:
      filedpapers-database:
        condition: service_healthy
      filedpapers-metascraper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - filedpapers-network

  filedpapers-database:
    image: mongodb/mongodb-community-server:8.2.2-ubuntu2204
    container_name: filedpapers-database
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - MONGODB_INITDB_DATABASE=${MONGODB_INITDB_DATABASE}
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    volumes:
      - filed_papers_mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - filedpapers-network

  filedpapers-metascraper:
    container_name: filedpapers-metascraper
    image: ghcr.io/svenkubiak/filedpapers/filedpapers-metascraper:${VERSION}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - filedpapers-network

networks:
  filedpapers-network:
    driver: bridge

volumes:
  filed_papers_mongodb_data: